"""initial_production_schema

Revision ID: 60b14c524674
Revises: 
Create Date: 2026-09-11 13:33:06.144781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60b14c524674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('messaging_style', sa.String(length=32), nullable=True),
    sa.Column('ai_persona', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_language_code'), ['language_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('native_language_code', sa.String(length=8), nullable=True),
    sa.Column('learning_language_code', sa.String(length=8), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('proficiency_level', sa.String(length=32), nullable=True),
    sa.Column('learning_goal', sa.String(length=64), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=16), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_period_end', sa.DateTime(), nullable=True),
    sa.Column('daily_messages_count', sa.Integer(), nullable=True),
    sa.Column('last_message_date', sa.Date(), nullable=True),
    sa.Column('auto_translate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['native_language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('vocabulary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('literal_meaning', sa.Text(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_term'), ['term'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('daily_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_day')
    )
    with op.batch_alter_table('daily_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_progress_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_progress_user_id'), ['user_id'], unique=False)

    op.create_table('email_verification_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_codes_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('password_reset_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_user_id'), ['user_id'], unique=False)

    op.create_table('saved_words',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_words_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_words_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_words_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('user_vocab_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_missed', sa.Integer(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name='uq_user_vocab')
    )
    with op.batch_alter_table('user_vocab_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('persona_name', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('turns_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_words',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'vocabulary_id', name='uq_lesson_word')
    )
    with op.batch_alter_table('lesson_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_words_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_words_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('lesson_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_words_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_words_lesson_id'))

    op.drop_table('lesson_words')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_language_code'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('user_vocab_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_next_review_at'))

    op.drop_table('user_vocab_progress')
    with op.batch_alter_table('saved_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_words_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_saved_words_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_words_created_at'))

    op.drop_table('saved_words')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_expires_at'))

    op.drop_table('password_reset_codes')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_scenario_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('email_verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_codes_expires_at'))

    op.drop_table('email_verification_codes')
    with op.batch_alter_table('daily_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_progress_date'))

    op.drop_table('daily_progress')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_term'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_language_code'))

    op.drop_table('vocabulary')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_language_code'))

    op.drop_table('scenarios')
    op.drop_table('languages')
    # ### end Alembic commands ###
